### ISSUE TITLE
[Error] Build Stopped: subcommand failed

### ISSUE THREAD

**Issue by TristonStuart** [mbbill/JSC.js#11]
Trying to build this project.
I am using windows 10.
I have this git clone and emsdk in a folder called jsc.
so emsdk : ./jsc/emsdk
this project : ./jsc/JSC.js
I installed Ninja to C:/Ninja and added it to my path.

Here are the commands I ran
`C:\Users\trist\Desktop\jsc\JSC.js>C:\Users\trist\Desktop\jsc\emsdk\emsdk_env.bat`
`C:\Users\trist\Desktop\jsc\JSC.js>C:\Users\trist\Desktop\jsc\JSC.js\buildtools\win\gn.exe gen out --args="target_os=\"wasm\""`
`C:\Users\trist\Desktop\jsc\JSC.js>ninja -C out`

Here is a pastebin of the error in full : https://pastebin.com/bZjE3xUH

Just a side note that the installation steps are outdated and the files reference do not exist (build/gn/download.bat) for example

**Comment by mbbill** [comment]
Yeah, the toolchain setup is a bit outdated. Let's see if I can find some time to fix it. Thanks for the report!

**Comment by TristonStuart** [comment]
**I just wanted to update. I tried some new things and it refuses to work. The error happens around [202/1094].**
**Here is the command causing the error :** https://pastebin.com/sJZZU3pg
**Here is the error I get if I manually run the command :** https://pastebin.com/4Wx0YQ1x
**Here is the full output including the error when running "ninja -C out" :** https://paste.ubuntu.com/p/WRrFKw5TBN/ (Apparently it is too big for pastebin)

**Comment by TristonStuart** [comment]
**Looks like the error is caused by missing files in ./out/obj/Source/JavaScriptCore
as well as it being weird with the directory.**
`error: unable to open output file 'obj/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.bc': 'no such file or directory'`

**Comment by mbbill** [comment]
hi, I just updated the build steps in README. would you mind try again? I was a bit outdated but I think it should be good now.

**Comment by TristonStuart** [comment]
> hi, I just updated the build steps in README. would you mind try again? I was a bit outdated but I think it should be good now.

![Capture37](https://user-images.githubusercontent.com/20646098/82131463-4ceb6e00-978a-11ea-87fa-185e49b70da6.PNG)

It says I didn't run the command when I did.

**Comment by mbbill** [comment]
that's something changed in EMSDK. seems like emsdk no longer defines the EMSCRIPTEN environment. I've updated the prep_env.bat and you may try again.

**Comment by TristonStuart** [comment]
That helps but I still run into errors :
`1 warning and 1 error generated.
em++: error: 'C:/Users/trist/Desktop/jsc/JSC.js/emsdk/upstream/bin\clang++.exe -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\include\libcxx -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\lib\libcxxabi\include -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\lib\libunwind\include -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\include\compat -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\include -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\include\libc -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\local\include -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\cache\wasm\include -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -MMD -MF obj/Source/JavaScriptCore/inspector/agents/InspectorScriptProfilerAgent.bc.d -DJSCJS=1 -DENABLE_JIT=0 -DENABLE_C_LOOP=1 -DLLIntOffsetsExtractor=CLoop -DNDEBUG -DNOMINMAX -DBUILDING_JavaScriptCore -DSTATICALLY_LINKED_WITH_WTF -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/ForwardingHeaders -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/inspector -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/yarr -I../Source/JavaScriptCore -I../Source/JavaScriptCore/API -I../Source/JavaScriptCore/assembler -I../Source/JavaScriptCore/bindings -I../Source/JavaScriptCore/builtins -I../Source/JavaScriptCore/bytecode -I../Source/JavaScriptCore/bytecompiler -I../Source/JavaScriptCore/dfg -I../Source/JavaScriptCore/disassembler -I../Source/JavaScriptCore/domjit -I../Source/JavaScriptCore/ftl -I../Source/JavaScriptCore/heap -I../Source/JavaScriptCore/debugger -I../Source/JavaScriptCore/inspector -I../Source/JavaScriptCore/inspector/agents -I../Source/JavaScriptCore/inspector/augmentable -I../Source/JavaScriptCore/inspector/remote -I../Source/JavaScriptCore/interpreter -I../Source/JavaScriptCore/jit -I../Source/JavaScriptCore/llint -I../Source/JavaScriptCore/parser -I../Source/JavaScriptCore/profiler -I../Source/JavaScriptCore/runtime -I../Source/JavaScriptCore/tools -I../Source/JavaScriptCore/wasm -I../Source/JavaScriptCore/wasm/js -I../Source/JavaScriptCore/yarr -I../Source/WTF -I../Source/icu -fvisibility=hidden -Wno-ignored-attributes -Wno-deprecated-register -Wno-nonportable-include-path -Wno-tautological-compare -Oz -m32 -std=c++17 -fno-exceptions -fvisibility-inlines-hidden -c ../Source/JavaScriptCore/inspector/agents/InspectorScriptProfilerAgent.cpp -Xclang -isystemC:\Users\trist\Desktop\jsc\JSC.js\emsdk\upstream\emscripten\system\include\SDL -c -o obj/Source/JavaScriptCore/inspector/agents/InspectorScriptProfilerAgent.bc -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
[5/649] CXX obj/Source/JavaScriptCore/inspector/agents/JSGlobalObjectDebuggerAgent.bc
FAILED: obj/Source/JavaScriptCore/inspector/agents/JSGlobalObjectDebuggerAgent.bc`

**Comment by mbbill** [comment]
`FAILED: obj/Source/JavaScriptCore/inspector/agents/JSGlobalObjectDebuggerAgent.bc`

is that all of the error message?

**Comment by TristonStuart** [comment]
> `FAILED: obj/Source/JavaScriptCore/inspector/agents/JSGlobalObjectDebuggerAgent.bc`
> 
> is that all of the error message?

This is the error I get if I manually run the command : 
`error: unable to open output file 'obj/Source/JavaScriptCore/inspector/agents/InspectorScriptProfilerAgent.bc':
      'no such file or directory'
1 error generated.`

**Comment by TristonStuart** [comment]
Any suggestions on how to fix?

**Comment by mbbill** [comment]
I'm using EMSDK from a year ago and everything seems fine. I'm not sure if this error is because of some changes in newer version emsdk. I'll find some time and try that. but before that I won't be able to know hot to fix it.
The error message itself looks very strange as how can it unable to open the output file? it complains about no such file or directory which doesn't make any sense. it is the output file and of course it doesn't exist.

**Comment by TristonStuart** [comment]
What version are you using I can try downloading that in the meantime?

**Comment by mbbill** [comment]
never mind. I just synced to the latest emsdk (1.39.16) and everything still working fine. and I'm still seeing environment "EMSCRIPTEN" being defined.

**Comment by TristonStuart** [comment]
I still get the same error with the newest version. But the older versions of emscripted give me this error : "compiler frontend failed to generate LLVM bitcode"

**Comment by TristonStuart** [comment]
How exactly are you installing emscripten. Could you try to redo all of the download steps?

**Comment by mbbill** [comment]
I cloned from their repo
https://github.com/emscripten-core/emsdk.git

**Comment by mbbill** [comment]
I think if you have trouble with emsdk, you might want to try with a wasm hello world. JSC.js is simply using emcc/emc++ just like any other wasm hello world project does. Nothing special here.

**Comment by TristonStuart** [comment]
> I think if you have trouble with emsdk, you might want to try with a wasm hello world. JSC.js is simply using emcc/emc++ just like any other wasm hello world project does. Nothing special here.

I verified that emsdk works fine with the hello world example outlined in their tutorial (https://emscripten.org/docs/getting_started/Tutorial.html#tutorial). I will try compiling jsc again.

**Comment by TristonStuart** [comment]
> I think if you have trouble with emsdk, you might want to try with a wasm hello world. JSC.js is simply using emcc/emc++ just like any other wasm hello world project does. Nothing special here.

I get a bunch of warnings as soon as I run the thing. Are you doing "emsdk install latest"? I also get an error and it stops : `1 warning and 1 error generated.
em++: error: 'C:/Users/trist/Desktop/jsc/emsdk/upstream/bin\clang++.exe -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\include\libcxx -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\lib\libcxxabi\include -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\lib\libunwind\include -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\include\compat -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\include -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\include\libc -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\local\include -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\cache\wasm\include -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -MMD -MF obj/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.bc.d -DJSCJS=1 -DENABLE_JIT=0 -DENABLE_C_LOOP=1 -DLLIntOffsetsExtractor=CLoop -DNDEBUG -DNOMINMAX -DBUILDING_JavaScriptCore -DSTATICALLY_LINKED_WITH_WTF -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/ForwardingHeaders -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/inspector -I../Source/JavaScriptCore/DerivedSources/JavaScriptCore/yarr -I../Source/JavaScriptCore -I../Source/JavaScriptCore/API -I../Source/JavaScriptCore/assembler -I../Source/JavaScriptCore/bindings -I../Source/JavaScriptCore/builtins -I../Source/JavaScriptCore/bytecode -I../Source/JavaScriptCore/bytecompiler -I../Source/JavaScriptCore/dfg -I../Source/JavaScriptCore/disassembler -I../Source/JavaScriptCore/domjit -I../Source/JavaScriptCore/ftl -I../Source/JavaScriptCore/heap -I../Source/JavaScriptCore/debugger -I../Source/JavaScriptCore/inspector -I../Source/JavaScriptCore/inspector/agents -I../Source/JavaScriptCore/inspector/augmentable -I../Source/JavaScriptCore/inspector/remote -I../Source/JavaScriptCore/interpreter -I../Source/JavaScriptCore/jit -I../Source/JavaScriptCore/llint -I../Source/JavaScriptCore/parser -I../Source/JavaScriptCore/profiler -I../Source/JavaScriptCore/runtime -I../Source/JavaScriptCore/tools -I../Source/JavaScriptCore/wasm -I../Source/JavaScriptCore/wasm/js -I../Source/JavaScriptCore/yarr -I../Source/WTF -I../Source/icu -fvisibility=hidden -Wno-ignored-attributes -Wno-deprecated-register -Wno-nonportable-include-path -Wno-tautological-compare -Oz -m32 -std=c++17 -fno-exceptions -fvisibility-inlines-hidden -c ../Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.cpp -Xclang -isystemC:\Users\trist\Desktop\jsc\emsdk\upstream\emscripten\system\include\SDL -c -o obj/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.bc -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
[343/1094] CXX obj/Source/JavaScriptCore/heap/SpaceTimeMutatorScheduler.bc
In file included from ../Source/JavaScriptCore/heap/SpaceTimeMutatorScheduler.cpp:27:
In file included from ../Source/JavaScriptCore/heap/SpaceTimeMutatorScheduler.h:28:
In file included from ../Source/JavaScriptCore/heap/MutatorScheduler.h:29:
In file included from ../Source/WTF\wtf/MonotonicTime.h:29:
In file included from ../Source/WTF\wtf/Seconds.h:28:
../Source/WTF\wtf/MathExtras.h:401:43: warning: implicit conversion from 'std::__2::numeric_limits<unsigned long long>::type' (aka 'unsigned long long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
        double fmodValue = fmod(trunc(d), std::numeric_limits<unsigned long long>::max() + 1.0);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
1 warning generated.`

**Comment by TristonStuart** [comment]
And if you could update the demo so it has access to the other exported variables that would be a big help while I am trying to solve this issue

**Comment by TristonStuart** [comment]
Honestly, if you tried it on another computer and could get it to work and sent me the exact steps it would probably help identify the error.

**Comment by mbbill** [comment]
LLVM changed a bunch of default behaviors and become backward incompatible. This is annoying. Anyway I've fixed the issues and you may try again.

**Comment by TristonStuart** [comment]
Whatever you did helped a lot but I get an error when linking to jsc.js
Here is the error: 
![Capture83](https://user-images.githubusercontent.com/20646098/82631633-d47e1600-9baa-11ea-9a99-0ea1262ac0f0.PNG)

**Comment by mbbill** [comment]
interesting. I can't repro the issue. It looks like something with the compiler but I'm already using the same one as you do.
