### ISSUE TITLE
Error When Building With target_os=win

### ISSUE THREAD

**Issue by TristonStuart** [mbbill/JSC.js#12]
gn gen out --args="target_os=\"win\""
ninja -C out
Error : `ninja: Entering directory "out"
[1/1096] CXX obj/Source/JavaScriptCore/bytecode/ArrayAllocationProfile.obj
FAILED: obj/Source/JavaScriptCore/bytecode/ArrayAllocationProfile.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/ArrayAllocationProfile.obj.rsp /c ../Source/JavaScriptCore/bytecode/ArrayAllocationProfile.cpp /Foobj/Source/JavaScriptCore/bytecode/ArrayAllocationProfile.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[2/1096] CXX obj/Source/JavaScriptCore/bytecode/CallLinkStatus.obj
FAILED: obj/Source/JavaScriptCore/bytecode/CallLinkStatus.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/CallLinkStatus.obj.rsp /c ../Source/JavaScriptCore/bytecode/CallLinkStatus.cpp /Foobj/Source/JavaScriptCore/bytecode/CallLinkStatus.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[3/1096] CXX obj/Source/JavaScriptCore/bytecode/CallVariant.obj
FAILED: obj/Source/JavaScriptCore/bytecode/CallVariant.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/CallVariant.obj.rsp /c ../Source/JavaScriptCore/bytecode/CallVariant.cpp /Foobj/Source/JavaScriptCore/bytecode/CallVariant.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[4/1096] CXX obj/Source/JavaScriptCore/bytecode/CodeBlockHash.obj
FAILED: obj/Source/JavaScriptCore/bytecode/CodeBlockHash.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/CodeBlockHash.obj.rsp /c ../Source/JavaScriptCore/bytecode/CodeBlockHash.cpp /Foobj/Source/JavaScriptCore/bytecode/CodeBlockHash.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[5/1096] CXX obj/Source/JavaScriptCore/bytecode/BytecodeBasicBlock.obj
FAILED: obj/Source/JavaScriptCore/bytecode/BytecodeBasicBlock.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/BytecodeBasicBlock.obj.rsp /c ../Source/JavaScriptCore/bytecode/BytecodeBasicBlock.cpp /Foobj/Source/JavaScriptCore/bytecode/BytecodeBasicBlock.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[6/1096] CXX obj/Source/JavaScriptCore/bytecode/BytecodeGeneratorification.obj
FAILED: obj/Source/JavaScriptCore/bytecode/BytecodeGeneratorification.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/BytecodeGeneratorification.obj.rsp /c ../Source/JavaScriptCore/bytecode/BytecodeGeneratorification.cpp /Foobj/Source/JavaScriptCore/bytecode/BytecodeGeneratorification.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[7/1096] CXX obj/Source/JavaScriptCore/bindings/ScriptValue.obj
FAILED: obj/Source/JavaScriptCore/bindings/ScriptValue.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bindings/ScriptValue.obj.rsp /c ../Source/JavaScriptCore/bindings/ScriptValue.cpp /Foobj/Source/JavaScriptCore/bindings/ScriptValue.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[8/1096] CXX obj/Source/JavaScriptCore/bytecode/BytecodeLivenessAnalysis.obj
FAILED: obj/Source/JavaScriptCore/bytecode/BytecodeLivenessAnalysis.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/BytecodeLivenessAnalysis.obj.rsp /c ../Source/JavaScriptCore/bytecode/BytecodeLivenessAnalysis.cpp /Foobj/Source/JavaScriptCore/bytecode/BytecodeLivenessAnalysis.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[9/1096] CXX obj/Source/JavaScriptCore/bytecode/AccessCase.obj
FAILED: obj/Source/JavaScriptCore/bytecode/AccessCase.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/AccessCase.obj.rsp /c ../Source/JavaScriptCore/bytecode/AccessCase.cpp /Foobj/Source/JavaScriptCore/bytecode/AccessCase.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
[10/1096] CXX obj/Source/JavaScriptCore/bytecode/AccessCaseSnippetParams.obj
FAILED: obj/Source/JavaScriptCore/bytecode/AccessCaseSnippetParams.obj
cl.exe /showIncludes /FC @obj/Source/JavaScriptCore/bytecode/AccessCaseSnippetParams.obj.rsp /c ../Source/JavaScriptCore/bytecode/AccessCaseSnippetParams.cpp /Foobj/Source/JavaScriptCore/bytecode/AccessCaseSnippetParams.obj /Fd"obj/Source/JavaScriptCore/jsc.pdb"
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.`

Files are missing.

**Comment by mbbill** [comment]
I just updated the README, would you mind try again with the updated steps? thanks!
