### ISSUE TITLE
Failed at checkSyntax

### ISSUE THREAD

**Issue by Kudo** [mbbill/JSC.js#19]
hi! do you remember which version of emsdk you used? i use the latest (3.1.10) and there were compile errors where i can bypass which the following change:

```diff
--- a/Source/WTF/wtf/Compiler.h
+++ b/Source/WTF/wtf/Compiler.h
@@ -167,7 +167,8 @@
 /* In GCC functions marked with no_sanitize_address cannot call functions that are marked with always_inline and not marked with no_sanitize_address.
  * Therefore we need to give up on the enforcement of ALWAYS_INLINE when bulding with ASAN. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67368 */
 #if !defined(ALWAYS_INLINE) && COMPILER(GCC_COMPATIBLE) && defined(NDEBUG) && !COMPILER(MINGW) && !(COMPILER(GCC) && ASAN_ENABLED)
-#define ALWAYS_INLINE inline __attribute__((__always_inline__))
+// #define ALWAYS_INLINE inline __attribute__((__always_inline__))
+#define ALWAYS_INLINE inline
 #endif

 #if !defined(ALWAYS_INLINE) && COMPILER(MSVC) && defined(NDEBUG)
* Unmerged path build/BUILD.gn
```

however, the jsc_eval always reports an error from whatever given js input, even the simple one like `1 + 1`.
the code will fail at this point where errMsg is `: -1`
https://github.com/mbbill/JSC.js/blob/fc2a917e8a83424fdbd008a8c9202383312855c6/Source/JavaScriptCore/JSCJS/jscjs.cpp#L187-L191

**Comment by mbbill** [comment]
that's a pretty old version. I can't remember the exact version number but that's was in mid 2019

**Comment by Kudo** [comment]
thanks! could you help to check whether the latest emsdk work for you when you get a chance?

**Comment by mbbill** [comment]
Yeah I just compiled with the latest emsdk. there were a bunch of linking errors but that was an easy fix. But eventually the generated binary doesn't work for some reason. I got `:-1` as you did. I don't quite have much time to fix it atm unfortunately.

**Comment by Kudo** [comment]
what i want is for emscripten to output ESM format. i can workaround it by editing `demo/jsc.js` manually. thanks for taking a look anyway 😁  i'm closing this issue.
