### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rafaelcaricio** [mbbill/JSC.js#9]
This project looks great. I would like to use it for another project I am working on. But I am not sure if I can use this project since I cannot find a license file. Would you be so kind to add the license you choose to the repository?

Thank you and nice work!

**Comment by mbbill** [comment]
It's LGPL.
JavaScriptCore is LGPL, and all my changes are also on LGPL.

**Comment by rafaelcaricio** [comment]
Thank you for the reply.
